require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SteplistsController do

  # This should return the minimal set of attributes required to create a valid
  # Steplist. As you add validations to Steplist, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all steplists as @steplists" do
      steplist = Steplist.create! valid_attributes
      get :index
      assigns(:steplists).should eq([steplist])
    end
  end

  describe "GET show" do
    it "assigns the requested steplist as @steplist" do
      steplist = Steplist.create! valid_attributes
      get :show, :id => steplist.id
      assigns(:steplist).should eq(steplist)
    end
  end

  describe "GET new" do
    it "assigns a new steplist as @steplist" do
      get :new
      assigns(:steplist).should be_a_new(Steplist)
    end
  end

  describe "GET edit" do
    it "assigns the requested steplist as @steplist" do
      steplist = Steplist.create! valid_attributes
      get :edit, :id => steplist.id
      assigns(:steplist).should eq(steplist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Steplist" do
        expect {
          post :create, :steplist => valid_attributes
        }.to change(Steplist, :count).by(1)
      end

      it "assigns a newly created steplist as @steplist" do
        post :create, :steplist => valid_attributes
        assigns(:steplist).should be_a(Steplist)
        assigns(:steplist).should be_persisted
      end

      it "redirects to the created steplist" do
        post :create, :steplist => valid_attributes
        response.should redirect_to(Steplist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved steplist as @steplist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Steplist.any_instance.stub(:save).and_return(false)
        post :create, :steplist => {}
        assigns(:steplist).should be_a_new(Steplist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Steplist.any_instance.stub(:save).and_return(false)
        post :create, :steplist => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested steplist" do
        steplist = Steplist.create! valid_attributes
        # Assuming there are no other steplists in the database, this
        # specifies that the Steplist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Steplist.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => steplist.id, :steplist => {'these' => 'params'}
      end

      it "assigns the requested steplist as @steplist" do
        steplist = Steplist.create! valid_attributes
        put :update, :id => steplist.id, :steplist => valid_attributes
        assigns(:steplist).should eq(steplist)
      end

      it "redirects to the steplist" do
        steplist = Steplist.create! valid_attributes
        put :update, :id => steplist.id, :steplist => valid_attributes
        response.should redirect_to(steplist)
      end
    end

    describe "with invalid params" do
      it "assigns the steplist as @steplist" do
        steplist = Steplist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Steplist.any_instance.stub(:save).and_return(false)
        put :update, :id => steplist.id, :steplist => {}
        assigns(:steplist).should eq(steplist)
      end

      it "re-renders the 'edit' template" do
        steplist = Steplist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Steplist.any_instance.stub(:save).and_return(false)
        put :update, :id => steplist.id, :steplist => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested steplist" do
      steplist = Steplist.create! valid_attributes
      expect {
        delete :destroy, :id => steplist.id
      }.to change(Steplist, :count).by(-1)
    end

    it "redirects to the steplists list" do
      steplist = Steplist.create! valid_attributes
      delete :destroy, :id => steplist.id
      response.should redirect_to(steplists_url)
    end
  end

end
